### ISSUE TITLE
Custom badge

### ISSUE THREAD

**Issue by LucBerge** [azu/voting-badge#4]
Hi ! It would be nice to be able to customize the badge using [Shield.io](https://shields.io/) parameters.

I would like to be able to change:
+ The label
+ The color
+ The style

I tried to use the [Shield.io endpoint](https://shields.io/endpoint) but it is impossible since you are not using a json endpoint for https://voting-badge.herokuapp.com/count

**Comment by LucBerge** [comment]
@azu check out this [PR](https://github.com/azu/voting-badge/pull/5) ! I couldn't test though

**Comment by LucBerge** [comment]
I just tried but it's not working. When will it be deployed ?

**Comment by LucBerge** [comment]
@azu I just tried but it's not working. When will it be deployed ?

**Comment by azu** [comment]
Deploy is failed because of This app use old stack.

```
-----> Building on the Heroku-20 stack

-----> Multipack app detected

=====> Downloading Buildpack: https://github.com/mojodna/heroku-buildpack-cairo.git

=====> Detected Framework: Cairo

-----> Vendoring binaries

       Fetching https://s3.amazonaws.com/mojodna-heroku/heroku-20/cairo-1.14.6-1.tar.gz

gzip: stdin: not in gzip format

tar: Child returned status 1

tar: Error is not recoverable: exiting now

 !     Push rejected, failed to compile Multipack app.

 !     Push failed

```

**Comment by LucBerge** [comment]
Ok, I'll try to fix it.

**Comment by LucBerge** [comment]
Ok, I don't understand how to fix it, I'm not used to Heroku,.. Do you think you could do it please ?

**Comment by LucBerge** [comment]
Ok, I don't understand how to fix it, I'm not used to Heroku,.. Do you think you could do it please @azu ?

**Comment by azu** [comment]
Probably, this error depended on node-canvas.
https://github.com/azu/voting-badge/blob/4abcb46ed936ec660bf45edb6ada19259ad7f50a/lib/badge-service.js#L2

I'm not so sure about that old gh-badges require node-canvas.
Drop `gh-badges` and just return `https://img.shields.io/badge/*` like [this](https://github.com/azu/voting-badge/blob/4abcb46ed936ec660bf45edb6ada19259ad7f50a/lib/badge-service.js#L5), it may be worked without node-canvas.

However, I no longer use this app and it is hard to maintain.
If you can, I can transfer ownership of this app. Thanks to work.

**Comment by LucBerge** [comment]
Thanks for the tip, I'll try it tomorrow

**Comment by LucBerge** [comment]
Yes, I guess it is beter not using the `gh-badges` package.

> I can transfer ownership of this app.

Why not
